### ISSUE TITLE
Bug..? app doesnt launch as its supposed to

### ISSUE THREAD

**Issue by Lolguy8321** [muzik-apps/Muzik-offline#58]
**Describe the bug**
Alrighty so idek whats wrong but i followed the basic guide for installing and everything goes through except the app itself doesnt run for sum reason i tried 2 of the windows setup thingys both the msi and setup files but nothing works i did also try running as administrator but even that didnt work..

**To Reproduce**
1. Download as usual
2. install
3. Run app
4. nothing happens :/

**Expected behavior**
the app to work as normal lol wit the gui and everything and to jam ofc

**Screenshots**

**Desktop (please complete the following information):**
 - OS:Windows
 - Browser: FireFox i do have chrome as well tho
 - Version i believe this is windows version? i have a custom version of windows but heres the build version 22h2 19045.3803

**Additional context**

**Comment by waveyboym** [comment]
Hi @Lolguy8321, thank you for submitting an issue.

My first assumption for something like this is that you may not have microsoft edge browser installed. The browser should come pre-installed with windows builds, but since you said you have a custom build, I am assuming that this may be the case. The app depends on this in order to serve you the UI: <a href="https://tauri.app/v1/references/webview-versions/#webview2-windows">requirements</a>
Here is a download link in case you don't have it: <a href="https://www.microsoft.com/en-us/edge/download?form=MA13FJ">edge</a>

However if that is not the issue, then I would like to ask for some more details:
1. Which version of the app did you download and attempt to run. You can normally see the version of the app as part of the name of the file you downloaded, eg ```muzik-offline_0.x.0_x64-setup.exe```?
2. Which version of Microsoft Edge do you have. You can find this information in the Settings -> About Microsoft Edge of the browser?
3. Could you launch the app from the terminal and report any errors thrown: 
- Open the Windows terminal.
- In the terminal, navigate to where you stored the app when you download, eg ```C:\Users\User\AppData\Local\muzik-offline```
- Once in the correct directory, you can run the app by typing ```muzik-offline.exe``` and pressing Enter.
- If any errors occur during the launch process, they will be displayed in the terminal window. Copy whatever is printed out and paste it here as a comment.

**Comment by waveyboym** [comment]
Hi @Lolguy8321. Has your issue been resolved?
