### ISSUE TITLE
[FEATURE REQUEST] Music Library

### ISSUE THREAD

**Issue by Crocodile73** [muzik-apps/Muzik-offline#70]
Can you add the ability to choose the library directory as one single folder?. The only way currently i can get my albums, is by adding them individually.

**Comment by waveyboym** [comment]
Hi @Crocodile73 , thank you for submitting a feature request.

I would just like some more information in what exactly you are seeking?
1. Do you want to have a singular folder that contains multiple folders where each of these folders contain music. If that is what your seek, then this feature ***DOES NOT*** already exist, because by default, scanning is ***NOT*** recursive.
2. Do you want to have a better UI for managing your paths, like to easily add type out and singular paths, delete singular paths or select paths(this will be coming in the next v0.6.0 release)?
3. Something else that I am missing and if so please can you explain with greater details.

**Comment by Crocodile73** [comment]
Your first point is the one I mean. However for me if I add my folder to the directory, it does not find anything. Example D:\Johns Music\ has all folders for my albums which have mp3 in them. It finds nothing. Only if I add the actual album folder name to the path will it show it.

**Comment by waveyboym** [comment]
Hi @Crocodile73 , After going through the codebase, I discovered the ability to scan folders was actually removed in the early stages. The reason being due to security reasons. We wouldn't have wanted the app to be able to scan a users entire drive if say they gave their C drive for example.
However, considering you want this feature, I will add it as an advanced option that you can toggle such that you can consent as to whether or not you want directories to be scanned recursively. However, by default it will be disabled(due to security reasons).
Since this is not a large feature, please look out for the next patch <a href="https://github.com/muzik-apps/muzik-offline/releases">release</a> of v0.6.2 hopefully by the end of this week.

**Comment by Crocodile73** [comment]
Appreciate you doing that. Thank you
