### ISSUE TITLE
browse folders

### ISSUE THREAD

**Issue by senolfndk** [muzik-apps/Muzik-offline#91]
music folder not added
![Ekran görüntüsü 2024-12-07 135202](https://github.com/user-attachments/assets/8026fcbc-77ba-4570-a4a1-ce61c99f2a1a)

**Comment by waveyboym** [comment]
Hi @senolfndk , I have some questions:
1. Is this a fresh install of the app?
2. What version are you using? (you can see this by clicking settings and then about)
3. Did you have a previous version of the app and then install a new version when you upgraded? (if you did, you should have deleted all previous app data as specified in <a href="https://github.com/muzik-apps/muzik-offline/releases/tag/v0.6.1">v0.6.1</a> as new breaking changes were introduced)
4. What OS are you using?
5. When you downloaded your binary, which binary did you download?
6. What happens if you click on the settings button, then click on Music Folders? Does it load normally or does the app go blank?

Either way, the easiest way to fix this is to completely delete the app and all it's related data and install a fresh install as if you are installing the app for the first time.

**Comment by senolfndk** [comment]
yes i did a clean install
Windows 11 pro 24H2
![Ekran görüntüsü 2024-12-07 142925](https://github.com/user-attachments/assets/c4f51035-b1fc-4d2c-aaff-5b101ef09e2c)

**Comment by senolfndk** [comment]
yes i did a clean install
![Ekran görüntüsü 2024-12-07 142925](https://github.com/user-attachments/assets/67610af4-9307-4ff3-899f-1fc8ce1acaa3)
Windows 11 pro 24H2

**Comment by senolfndk** [comment]
yes i did a clean install
![Ekran görüntüsü 2024-12-07 142925](https://github.com/user-attachments/assets/f903d094-fe69-4bc4-9ded-c8bcc803c572)

**Comment by senolfndk** [comment]
Windows 11 pro 24H2

**Comment by waveyboym** [comment]
@senolfndk 
I am having a very difficult time replicating this issue. I tried with both .msi and .exe files and with fresh installs, everything seems to work just fine on my side. I did notice however that if I had the .msi app beforehand and then delete it and then install another .msi app, it still preserves all of the app data from before. This is most likely the issue that you are experiencing.
So .msi apps **DO NOT** delete application data, you have to do it manually.
To fix this:
1. Completely delete the app.
2. Go to where the app stores application data(your home directory) and delete that folder. You should delete the ```muzik-offline-local-data``` folder permanently. The path for that is:
```
C:\Users\<your-username>\muzik-offline-local-data
```
3. Reinstall the app, either the .msi or .exe but just know that if you install the .msi version and there are new breaking updates in the future, then you will have to repeat the above process again.

I will document this in releases so that people who download .msi versions are aware of this

**Comment by waveyboym** [comment]
ok so you may have to:
1. Delete the app and delete the folder as specified in the command above.
2. Download the exe instead and install it
3. Uninstall it and select to delete application data
4. Reinstall that same exe and the problem should finally be resolved.

@senolfndk let me know if the problem is fixed

**Comment by senolfndk** [comment]
unfortunately same problem

**Comment by waveyboym** [comment]
@senolfndk , I have updated the app now. Please let me know if the new updates fix your problem. You no longer need to perform the previous heinous tasks since it's now automated. 
<a href="https://github.com/muzik-apps/muzik-offline/releases/tag/v0.7.0">release</a>

**Comment by senolfndk** [comment]
It works fine.
